修改日志的默认配置，增加时间、文件名、行号
wzpan/dingdang-robot pull request #64
Opened 2017-10-27 15:02 UTC by happycool333

2017-10-28 04:41 UTC, wzpan requested changes
代码风格不符合要求。请参见：https://travis-ci.org/wzpan/dingdang-robot/jobs/293729633
修改你的代码使之符合 pep8 的规范。

2017-10-28 10:30 UTC, wzpan requested changes
.gitignore 只能新增内容，不要随便删除数据。

另外看你的改动，估计还是不能满足 pep8 要求的。你也可以在本地装一下测试的工具，

``` sh
pip install coverage --cache-dir $HOME/.pip-cache
pip install nose --cache-dir $HOME/.pip-cache
pip install flake8 --cache-dir $HOME/.pip-cache
```

然后自己在 dingdang/ 目录下执行：

``` sh
sh test.sh
```

看看提示哪些格式错误（忽略 `nose.plugins.cover: ERROR: Coverage not available: unable to import coverage module` 及之后的错误）。

2017-10-29 00:41 UTC, happycool333 commented
已经通过CI build
.gitignore，是我误操作，已修改。

2017-10-29 01:48 UTC, wzpan approved these changes

2017-10-29 01:48 UTC, merged

2017-10-29 01:48 UTC, wzpan commented
Merged. Thanks!